# Generated by Django 6.0 on 2026-01-04 17:23

from django.db import migrations


def create_sample_tags(apps, schema_editor):
    tag_names = [
        "Bag",
        "Clothing",
        "Electronic",
        "Accessory",
        "Card",
        "Key",
        "Book/paper",
        "Stationery",
        "Sports",
        "Personal care",
        "Other",
    ]
    tag_model = apps.get_model('item', 'Tag')
    for name in tag_names:
        tag_model.objects.create(title=name)


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_tags),
    ]
