# Generated by Django 6.0 on 2026-01-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='replies_to',
        ),
    ]
