# Generated by Django 6.0 on 2026-02-22 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interaction", "0002_rename_parent_comment_replies_to"),
        ("item", "0004_item_latitude_item_longitude_alter_item_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="interaction.comment",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="item.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "item"), name="unique_user_item_report"
                    ),
                    models.UniqueConstraint(
                        fields=("user", "comment"), name="unique_user_comment_report"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("comment__isnull", True), ("item__isnull", False)
                            ),
                            models.Q(
                                ("comment__isnull", False), ("item__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="report_must_have_exactly_one_target",
                    ),
                ],
            },
        ),
    ]
